/** Every chord the studio registers, as Playwright presses them. */
export const registeredChords = {
  copy: ['ControlOrMeta+c'],
  cut: ['ControlOrMeta+x'],
  paste: ['ControlOrMeta+v'],
  duplicate: ['ControlOrMeta+d'],
  'edit-geometry': ['Shift+p'],
  'reconnect-source': ['Shift+s'],
  'reconnect-target': ['Shift+t'],
  'toggle-flow-direction': ['Shift+d'],
  'reverse-flow': ['Shift+r'],
  'toggle-boundary-shape': ['Shift+b'],
  'align-left': ['ControlOrMeta+Shift+ArrowLeft'],
  'align-centre': ['ControlOrMeta+Shift+h'],
  'align-right': ['ControlOrMeta+Shift+ArrowRight'],
  'align-top': ['ControlOrMeta+Shift+ArrowUp'],
  'align-middle': ['ControlOrMeta+Shift+v'],
  'align-bottom': ['ControlOrMeta+Shift+ArrowDown'],
  'distribute-horizontal': ['ControlOrMeta+Shift+d'],
  'distribute-vertical': ['ControlOrMeta+Shift+b'],
  'snap-to-grid': ['ControlOrMeta+Shift+g'],
  'reset-zoom': ['ControlOrMeta+1'],
  'fit-selection': ['ControlOrMeta+Shift+0'],
  'next-diagram': ['PageDown'],
  'previous-diagram': ['PageUp'],
  'new-diagram': [],
  'rename-diagram': [],

  open: ['ControlOrMeta+o'],
  save: ['ControlOrMeta+s'],
  'save-as': ['ControlOrMeta+Shift+s'],
  'export-diagram': [],
  'export-register': [],
  'export-typst': [],
  'export-pdf': [],
  'export-png': [],
  share: [],
  'close-file': ['ControlOrMeta+Shift+x'],
  undo: ['ControlOrMeta+z'],
  redo: ['ControlOrMeta+Shift+z', 'Control+y'],
  delete: ['Delete', 'Backspace'],
  rename: ['F2'],
  'model-panel': ['m'],
  'focus-threats': ['t'],
  'select-all': ['ControlOrMeta+a'],
  'fit-to-view': ['ControlOrMeta+0'],
  'zoom-in': ['ControlOrMeta+=', 'ControlOrMeta++'],
  'zoom-out': ['ControlOrMeta+-'],
  'start-flow': ['f'],
  'add-bend': ['+'],
  'select-tool': ['v', 'Escape', '1'],
  'hand-tool': ['h', 'Space'],
  'actor-tool': ['a', '2'],
  'process-tool': ['p', '3'],
  'store-tool': ['s', '4'],
  'boundary-box-tool': ['b', '5'],
  'boundary-curve-tool': ['c', '6'],
  'note-tool': ['n', '7'],
  'shortcut-reference': ['?', 'F1'],
} as const;
