import {
  assumptionIdSchema,
  diagramIdSchema,
  elementIdSchema,
  mitigationIdSchema,
  threatIdSchema,
} from './ids.js';
import { modelSchema } from './model.js';
import { acceptsEveryCharacter } from './text.js';

type CheckDef = {
  readonly check: string;
  readonly minimum?: number;
  readonly maximum?: number;
  readonly value?: number;
  readonly inclusive?: boolean;
  readonly fn?: unknown;
};

type Check = { readonly _zod: { readonly def: CheckDef } };

type SchemaDef = {
  readonly type: string;
  readonly format?: string;
  readonly checks?: readonly Check[];
  readonly shape?: Readonly<Record<string, Schema>>;
  readonly options?: readonly Schema[];
  readonly discriminator?: string;
  readonly entries?: Readonly<Record<string, string>>;
  readonly values?: readonly string[];
  readonly element?: Schema;
  readonly innerType?: Schema;
};

type Schema = { readonly def: SchemaDef };

const brands: readonly (readonly [Schema, string])[] = [
  [elementIdSchema, 'ElementId'],
  [diagramIdSchema, 'DiagramId'],
  [threatIdSchema, 'ThreatId'],
  [mitigationIdSchema, 'MitigationId'],
  [assumptionIdSchema, 'AssumptionId'],
];

const preamble = [
  'The whole internal model, expanded from the zod schemas that define it.',
  '`parseModel` is the only way a model value comes into existence, and it',
  'enforces more than the shapes below: element, diagram, threat, mitigation',
  'and assumption ids unique where they must be, threat numbers unique and',
  'never above `lastIssuedThreatNumber`, flow endpoints anchored inside their',
  'own diagram and never to the flow itself, and every element and threat',
  'reference resolving.',
  '',
  'A field of type `text` accepts every letter, mark, number, punctuation,',
  'symbol and space separator Unicode defines, plus tab, line feed and',
  'carriage return, plus the format characters a script owns: every one',
  'Unicode gives a script of its own, the Arabic number signs and letter',
  'mark, the Syriac abbreviation mark, the Mongolian vowel separator and',
  'the Kaithi and Egyptian hieroglyph format controls among them, together',
  'with the zero width non-joiner U+200C, the zero width joiner U+200D and',
  'the Arabic marks U+0605, U+06DD and U+08E2 that Unicode files as',
  'belonging to no script. The Arabic letter mark U+061C is a bidirectional',
  'control that Unicode gives the Arabic script, so it is accepted.',
  '',
  'It refuses the rest: every other control character, the format',
  'characters no script owns, among them the soft hyphen U+00AD, the',
  'bidirectional controls U+200E, U+200F, U+202A to U+202E and U+2066 to',
  'U+2069, the zero width space U+200B, the word joiner and the invisible',
  'operators U+2060 to U+206F, the byte order mark U+FEFF and the tag',
  'characters, so a subdivision flag built from tags is refused where every',
  'other emoji sequence is not, the line and paragraph separators U+2028 and',
  'U+2029, private use, unassigned code points, and an unpaired surrogate.',
  'The empty string is text, and a field carrying a length says so beside',
  'its type.',
  '',
  'Generated by `src/lib/schema-report.fixtures.ts` and checked against the schemas on',
  'every test run. Regenerate it with `pnpm snapshots:update @saerskriven/model`.',
];

/** The internal model schema as markdown, generated from `modelSchema` with every field expanded where it stands. */
export function renderModelSchema(): string {
  return [
    '# Internal model schema',
    '',
    ...preamble,
    '',
    renderSchema(modelSchema),
    '',
  ].join('\n');
}

/**
 * One schema's fields as markdown. A check it has no words for is omitted,
 * and a field carrying the model's character rule prints as `text`.
 */
export function renderSchema(schema: Schema): string {
  return expand(schema, '').join('\n');
}

function expand(schema: Schema, indent: string): string[] {
  const def = schema.def;
  if (def.type === 'optional' && def.innerType) {
    return expand(def.innerType, indent);
  }
  if (def.shape) {
    return Object.entries(def.shape).flatMap(([name, field]) =>
      fieldLines(name, field, indent),
    );
  }
  if (def.element) {
    return expand(def.element, indent);
  }
  const discriminator = def.discriminator;
  if (def.options && discriminator !== undefined) {
    return def.options.flatMap((option) =>
      variant(option, discriminator, indent),
    );
  }
  return [];
}

function fieldLines(name: string, schema: Schema, indent: string): string[] {
  return [
    `${indent}- \`${name}\`: ${summary(schema)}`,
    ...expand(schema, `${indent}  `),
  ];
}

function variant(
  option: Schema,
  discriminator: string,
  indent: string,
): string[] {
  const shape = { ...option.def.shape };
  return [
    `${indent}- when \`${discriminator}\` is ${summary(shape[discriminator])}`,
    ...Object.entries(shape)
      .filter(([name]) => name !== discriminator)
      .flatMap(([name, field]) => fieldLines(name, field, `${indent}  `)),
  ];
}

function summary(schema: Schema): string {
  const def = schema.def;
  const brand = brands.find(([branded]) => branded === schema);
  if (brand) {
    return `${brand[1]} (${scalar(def)})`;
  }
  if (def.type === 'optional' && def.innerType) {
    return `optional, ${summary(def.innerType)}`;
  }
  if (def.shape) {
    return 'object';
  }
  if (def.element) {
    return `list of ${listed(def)}${summary(def.element)}`;
  }
  if (def.options) {
    const total = `one of ${String(def.options.length)}`;
    return def.discriminator === undefined
      ? total
      : `${total}, told apart by \`${def.discriminator}\``;
  }
  if (def.entries) {
    return `one of ${Object.values(def.entries)
      .map((value) => `\`${value}\``)
      .join(', ')}`;
  }
  if (def.values) {
    return def.values.map((value) => `\`${value}\``).join(' or ');
  }
  return scalar(def);
}

function listed(def: SchemaDef): string {
  const least = (def.checks ?? []).find(
    (check) => check._zod.def.check === 'min_length',
  )?._zod.def.minimum;
  return least === undefined ? '' : `at least ${String(least)} `;
}

function scalar(def: SchemaDef): string {
  const checks = def.checks ?? [];
  const bounds = checks.flatMap((check) => bound(check._zod.def));
  return [kind(def, checks), ...bounds].join(', ');
}

function kind(def: SchemaDef, checks: readonly Check[]): string {
  if (checks.some((check) => check._zod.def.fn === acceptsEveryCharacter)) {
    return 'text';
  }
  return def.format === 'safeint' ? 'integer' : def.type;
}

function bound(check: CheckDef): string[] {
  if (check.check === 'min_length') {
    return characters('at least', check.minimum);
  }
  if (check.check === 'max_length') {
    return characters('at most', check.maximum);
  }
  if (check.check === 'greater_than') {
    return limit(check.value, (amount) =>
      check.inclusive === true ? `${amount} or more` : `greater than ${amount}`,
    );
  }
  if (check.check === 'less_than') {
    return limit(check.value, (amount) =>
      check.inclusive === true ? `${amount} or less` : `less than ${amount}`,
    );
  }
  return [];
}

function characters(wording: string, count: number | undefined): string[] {
  return count === undefined
    ? []
    : [`${wording} ${String(count)} character${count === 1 ? '' : 's'}`];
}

function limit(
  value: number | undefined,
  phrase: (amount: string) => string,
): string[] {
  return value === undefined ? [] : [phrase(String(value))];
}
