import type { z } from 'zod';
import type { modelSchema } from './model.js';

/**
 * Hand-authored model covering the vocabulary `ecluseFixture` never reaches,
 * so the two together span every construct the model declares. It stays
 * separate so that fixture remains a faithful transcription of its source.
 * Typed as the schema's input: specs feed it through parseModel.
 */
export const vocabularyComplementFixture: z.input<typeof modelSchema> = {
  metadata: {
    title: 'Vocabulary complement',
    owner: 'Alexandra de Wit',
    description: 'Sample model covering what the Écluse fixture leaves unused.',
    contributors: ['Alexandra de Wit', 'Jonas Lindqvist'],
  },
  diagrams: [
    {
      id: 'diagram-complement',
      title: 'Complement',
      elements: [
        {
          kind: 'trust-boundary',
          id: 'element-shoreline',
          name: 'Shoreline',
          description: 'Freehand boundary drawn around the tidal zone.',
          outOfScope: false,
          reasonOutOfScope: '',
          shape: {
            kind: 'curve',
            waypoints: [
              { x: 0, y: 0 },
              { x: 120, y: 40 },
              { x: 240, y: 20 },
            ],
          },
        },
        {
          kind: 'text',
          id: 'element-archive-note',
          name: '',
          description: '',
          outOfScope: false,
          reasonOutOfScope: '',
          position: { x: 40, y: 20 },
          size: { width: 200, height: 60 },
          text: 'Tapes are read only on the standby drive.',
        },
        {
          kind: 'store',
          id: 'element-tape-archive',
          name: 'Tape archive',
          description: 'Offline copies of the ledger, written nightly.',
          outOfScope: true,
          reasonOutOfScope: 'Held and operated by the records department.',
          position: { x: 40, y: 120 },
          size: { width: 160, height: 80 },
        },
      ],
    },
  ],
  threats: [
    {
      id: 'threat-vocab-linking',
      number: 1,
      title: 'Archive reads link a reader across visits',
      category: { methodology: 'LINDDUN', category: 'linking' },
      severity: 'undecided',
      status: 'not-applicable',
      description: 'The archive predates the records it would have to link.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-identifying',
      number: 2,
      title: 'Retrieval logs identify the reader behind a pseudonym',
      category: { methodology: 'LINDDUN', category: 'identifying' },
      severity: 'low',
      status: 'open',
      description: 'A retrieval log records the requesting workstation.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-non-repudiation',
      number: 3,
      title: 'Signed retrieval receipts leave a reader no deniability',
      category: { methodology: 'LINDDUN', category: 'non-repudiation' },
      severity: 'low',
      status: 'mitigated',
      description: 'Each retrieval is signed with the reader private key.',
      elements: [],
    },
    {
      id: 'threat-vocab-detecting',
      number: 4,
      title: 'Response timing reveals that a record exists',
      category: { methodology: 'LINDDUN', category: 'detecting' },
      severity: 'medium',
      status: 'open',
      description: 'A hit and a miss take measurably different times.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-data-disclosure',
      number: 5,
      title: 'Restore output carries fields the reader may not see',
      category: { methodology: 'LINDDUN', category: 'data-disclosure' },
      severity: 'high',
      status: 'mitigated',
      description:
        'A restore returns whole records rather than the fields asked for.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-unawareness',
      number: 6,
      title: 'Readers are not told what the archive retains about them',
      category: { methodology: 'LINDDUN', category: 'unawareness' },
      severity: 'medium',
      status: 'accepted-risk',
      description: 'No notice describes the retrieval log to the people in it.',
      elements: [],
    },
    {
      id: 'threat-vocab-non-compliance',
      number: 7,
      title: 'Retention outlives the period the policy allows',
      category: { methodology: 'LINDDUN', category: 'non-compliance' },
      severity: 'high',
      status: 'open',
      description: 'Tapes are kept past the retention window without review.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-confidentiality',
      number: 8,
      title: 'Tapes leave the site unencrypted',
      category: { methodology: 'CIA', category: 'confidentiality' },
      severity: 'high',
      status: 'mitigated',
      description: 'A courier carries readable tapes between sites.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-integrity',
      number: 9,
      title: 'A restored ledger differs from the one written',
      category: { methodology: 'CIA', category: 'integrity' },
      severity: 'critical',
      status: 'open',
      description:
        'Nothing compares a restore against the source it came from.',
      elements: [],
    },
    {
      id: 'threat-vocab-availability',
      number: 10,
      title: 'The ledger is offline for the length of a restore',
      category: { methodology: 'CIA', category: 'availability' },
      severity: 'medium',
      status: 'open',
      description: 'A restore takes the ledger offline for its duration.',
      elements: [],
    },
    {
      id: 'threat-vocab-die-confidentiality',
      number: 11,
      title: 'The shipped index names every record on the tape',
      category: { methodology: 'CIA-DIE', category: 'confidentiality' },
      severity: 'medium',
      status: 'mitigated',
      description:
        'The index travels with the tape and is readable on its own.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-die-integrity',
      number: 12,
      title: 'A rewritten tape still passes the checksum it carries',
      category: { methodology: 'CIA-DIE', category: 'integrity' },
      severity: 'high',
      status: 'open',
      description: 'The checksum is stored on the tape it checks.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-die-availability',
      number: 13,
      title: 'One tape library is the only path to a restore',
      category: { methodology: 'CIA-DIE', category: 'availability' },
      severity: 'high',
      status: 'accepted-risk',
      description: 'No second reader exists for the tape format in use.',
      elements: [],
    },
    {
      id: 'threat-vocab-distributed',
      number: 14,
      title: 'Every copy of the archive sits in one building',
      category: { methodology: 'CIA-DIE', category: 'distributed' },
      severity: 'high',
      status: 'open',
      description: 'A fire at the records office destroys all copies at once.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-immutable',
      number: 15,
      title: 'An operator can overwrite a written tape',
      category: { methodology: 'CIA-DIE', category: 'immutable' },
      severity: 'critical',
      status: 'mitigated',
      description: 'Write protection is a policy rather than a mechanism.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-ephemeral',
      number: 16,
      title: 'Boundary state outlives the session that drew it',
      category: { methodology: 'CIA-DIE', category: 'ephemeral' },
      severity: 'low',
      status: 'mitigated',
      description: 'Session state persists past the session.',
      elements: ['element-shoreline'],
    },
    {
      id: 'threat-vocab-oversight',
      number: 17,
      title: 'No one reviews an automated deletion before it runs',
      category: {
        methodology: 'PLOT4ai',
        category: 'accountability-and-human-oversight',
      },
      severity: 'high',
      status: 'open',
      description: 'The retention job deletes on a schedule with no approval.',
      elements: [],
    },
    {
      id: 'threat-vocab-bias',
      number: 18,
      title: 'Retention rules fall unevenly across record types',
      category: {
        methodology: 'PLOT4ai',
        category: 'bias-fairness-and-discrimination',
      },
      severity: 'medium',
      status: 'accepted-risk',
      description: 'Some record types are kept far longer than others.',
      elements: [],
    },
    {
      id: 'threat-vocab-cybersecurity',
      number: 19,
      title: 'Model inputs reach an unreviewed pipeline',
      category: { methodology: 'PLOT4ai', category: 'cybersecurity' },
      severity: 'high',
      status: 'accepted-risk',
      description: 'The ingestion pipeline has no review step.',
      elements: [],
    },
    {
      id: 'threat-vocab-governance',
      number: 20,
      title: 'Records enter the archive with no recorded owner',
      category: {
        methodology: 'PLOT4ai',
        category: 'data-and-data-governance',
      },
      severity: 'medium',
      status: 'open',
      description: 'Nothing names who answers for a record once it is filed.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-human-rights',
      number: 21,
      title: 'A subject cannot ask what the archive holds on them',
      category: {
        methodology: 'PLOT4ai',
        category: 'ethics-and-human-rights',
      },
      severity: 'medium',
      status: 'open',
      description: 'No route exists for a subject access request.',
      elements: [],
    },
    {
      id: 'threat-vocab-privacy',
      number: 22,
      title: 'Personal fields are archived beyond their purpose',
      category: {
        methodology: 'PLOT4ai',
        category: 'privacy-and-data-protection',
      },
      severity: 'high',
      status: 'mitigated',
      description: 'Whole records are archived rather than the fields needed.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-safety',
      number: 23,
      title: 'Tape disposal is not tracked to destruction',
      category: {
        methodology: 'PLOT4ai',
        category: 'safety-and-environmental-impact',
      },
      severity: 'low',
      status: 'mitigated',
      description: 'Retired tapes leave the site with no certificate returned.',
      elements: [],
    },
    {
      id: 'threat-vocab-transparency',
      number: 24,
      title: 'The retention schedule is not published',
      category: {
        methodology: 'PLOT4ai',
        category: 'transparency-and-accessibility',
      },
      severity: 'medium',
      status: 'not-applicable',
      description: 'The schedule is internal to the records department.',
      elements: [],
    },
    {
      id: 'threat-vocab-attack-modelling',
      number: 25,
      title: 'Attack tree omits the archive path',
      category: {
        methodology: 'custom',
        methodologyName: 'PASTA',
        category: 'attack-modelling',
      },
      severity: 'critical',
      status: 'open',
      description: 'No attack tree covers a restore from tape.',
      elements: [],
    },
    {
      id: 'threat-vocab-transferred',
      number: 26,
      title: 'Courier loses a tape between sites',
      category: { methodology: 'CIA', category: 'confidentiality' },
      severity: 'medium',
      status: 'transferred',
      description: 'Tapes travel by road between the two sites.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-avoided',
      number: 27,
      title: 'Self-service restore exposes another reader\u2019s records',
      category: { methodology: 'LINDDUN', category: 'data-disclosure' },
      severity: 'high',
      status: 'avoided',
      description: 'A self-service restore would read across reader records.',
      elements: ['element-tape-archive'],
    },
    {
      id: 'threat-vocab-eliminated',
      number: 28,
      title: 'Ledger credentials sit in the restore script',
      category: { methodology: 'CIA', category: 'integrity' },
      severity: 'critical',
      status: 'eliminated',
      description: 'The restore script once carried a database password.',
      elements: [],
    },
  ],
  lastIssuedThreatNumber: 28,
  mitigations: [
    {
      id: 'mitigation-vocab-proposed',
      title: 'Read replica during a restore',
      prose: 'Serve reads from a replica while the ledger restores.',
      status: 'proposed',
      threats: ['threat-vocab-availability'],
    },
    {
      id: 'mitigation-vocab-implemented',
      title: 'Drop session state on close',
      prose: 'Session state is discarded when the session closes.',
      status: 'implemented',
      threats: ['threat-vocab-ephemeral'],
    },
    {
      id: 'mitigation-vocab-verified',
      title: 'Archive retention audit',
      prose: 'The retention window is audited every quarter.',
      status: 'verified',
      threats: ['threat-vocab-linking', 'threat-vocab-non-compliance'],
    },
  ],
  assumptions: [
    {
      id: 'assumption-vocab-unconfirmed',
      prose: 'The archive vendor is thought to wipe returned tapes.',
      status: 'unconfirmed',
      threats: ['threat-vocab-linking'],
      appliesToModel: false,
    },
    {
      id: 'assumption-vocab-valid',
      prose: 'The records department encrypts every tape it holds.',
      status: 'valid',
      threats: ['threat-vocab-confidentiality'],
      appliesToModel: false,
    },
    {
      id: 'assumption-vocab-invalidated',
      prose: 'The ingestion pipeline was believed to be reviewed.',
      status: 'invalidated',
      threats: ['threat-vocab-cybersecurity'],
      appliesToModel: false,
    },
  ],
};
